{
 "title": "Principal Dashboard",
 "time": { "from": "2020-06-18T17:40:47.043Z", "to": "2020-06-19T05:40:47.043Z" },
 "templating": {
  "list": [
   {
    "name": "insid",
    "query": "select security_group_institutions.institution_id from security_users inner join security_group_users on security_group_users.security_user_id = security_users.id inner join security_group_institutions on security_group_institutions.security_group_id = security_group_users.security_group_id where  security_users.username = '${__user.login}'  group by security_group_institutions.institution_id limit 1"
   },
   {
    "name": "grade",
    "label": "Grade",
    "query": "\nselect code from education_grades"
   },
   {
    "name": "class",
    "label": "Classes",
    "query": "select name from institution_classes where institution_id = '$id'"
   }
  ]
 },
 "panels": [
  { "title": "Institution Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Institution Information",
   "type": "table-old",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "rawSql": "select * from institution_info_view where institution_id = '$insid'"
    }
   ]
  },
  {
   "title": "Students gender breakdown",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "select male, female, now() as time_sec from students_count_view where institution_id = '$insid'"
    }
   ]
  },
  {
   "title": "National level Student's BMI status",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 7, "x": 9, "y": 4 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "select *, now() as time_sec from students_count_by_bmi_view where institution_id = '$insid'"
    }
   ]
  },
  {
   "title": "Number of Students  By Grade",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 12 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "select *, now() as time_sec from  students_count_by_grade_view where  institution_id in (select security_group_institutions.institution_id from security_users inner join security_group_users on security_group_users.security_user_id = security_users.id inner join security_group_institutions on security_group_institutions.security_group_id = security_group_users.security_group_id where  security_users.username = '${__user.login}'  group by security_group_institutions.institution_id) limit 1"
    }
   ]
  },
  {
   "title": "Student Count List by Classes",
   "type": "table-old",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "rawSql": "select * from  student_count_by_class_view where  institution_id = '$insid'"
    }
   ]
  },
  { "title": "Bulk Upload Progress", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Bulk-upload Status ",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "rawSql": "select * from upload_count_view where institution_id = '$insid'"
    }
   ]
  },
  {
   "title": "Bulk-upload Status ",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 29 },
   "targets": [
    {
     "rawSql": "select * from upload_list_view where institution_id = '$insid'"
    }
   ]
  },
  {
   "title": "Students List",
   "type": "table-old",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 36 },
   "targets": [
    {
     "rawSql": "select * from students_list_view_table where institution_id = '$insid'"
    }
   ]
  }
 ]
}