{
 "title": "Principal Dashboard Copy",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "grade",
    "label": "Grade",
    "query": "select code from education_grades"
   },
   {
    "name": "insId",
    "query": "select security_group_institutions.institution_id from security_users inner join security_group_users on security_group_users.security_user_id = security_users.id inner join security_group_institutions on security_group_institutions.security_group_id = security_group_users.security_group_id where  security_users.username = '${__user.login}'  group by security_group_institutions.institution_id limit 1"
   },
   {
    "name": "class",
    "label": "Classes",
    "query": "select name from institution_classes where institution_id = $insId"
   }
  ]
 },
 "panels": [
  { "title": "Bulk Upload Progress", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "UPLOADS",
   "type": "table-old",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
   "targets": [
    {
     "rawSql": "-- select count(*) , created_at as time from uploads where $__timeFilter(created_at);\n\nselect * from uploads up inner join institution_classes ic on up.institution_class_id = ic.id\ninner join institutions i on ic.institution_id = i.id \ninner join institution_class_grades icg on ic.id = icg.institution_class_id\ninner join education_grades eg on eg.id = icg.education_grade_id\n-- where  i.id = $code\n-- and eg.code = '$grade'\n-- and $__timeFilter(created_at);\n-- select * from uploads  limit 10\n\n-- select count(*) from institution_students ist\n-- inner join institutions i on ist.institution_id = i.id\n-- inner join security_users stu on ist.student_id = stu.id\n-- inner join education_grades eg on eg.id = ist.education_grade_id\n-- where  i.id = $code\n-- and eg.code = '$grade'\n-- and stu.gender_id = 1"
    }
   ]
  },
  {
   "title": "PROCESSED",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "select count(*) , created_at as time from uploads where   is_processed != 0 and $__timeFilter(updated_at);"
    }
   ]
  },
  {
   "title": "UNPROCESSED dummy",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "select count(*) , created_at as time from uploads where   is_processed != 0 and $__timeFilter(updated_at);"
    }
   ]
  },
  {
   "title": "PROCESSING dummy",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "select count(*) , created_at as time from uploads where   is_processed != 0 and $__timeFilter(updated_at);"
    }
   ]
  },
  {
   "title": "SUCCESS-INSERT",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "select count(*) , created_at as time from uploads up where up.update = 1 and $__timeFilter(up.updated_at);"
    }
   ]
  },
  {
   "title": "PARTIAL SUCCESS-INSERT",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "select count(*) , created_at as time from uploads up where up.insert = 3 and $__timeFilter(up.updated_at);"
    }
   ]
  },
  {
   "title": "ERRORS-INSERT dummy",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "select count(*) , created_at as time from uploads up where up.insert = 3 and $__timeFilter(up.updated_at);"
    }
   ]
  },
  {
   "title": "EMAIL SENT",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "select count(*) , created_at as time from uploads up where up.is_email_sent in (1,2) and $__timeFilter(up.updated_at);"
    }
   ]
  },
  {
   "title": "SUCCESS - UPDATE",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 7 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "select count(*) , created_at as time from uploads up where up.update in  (1,3) and $__timeFilter(up.updated_at);"
    }
   ]
  },
  {
   "title": "PARTIAL SUCCESS-UPDATE dummy",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 7 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "select count(*) , created_at as time from uploads up where up.insert = 3 and $__timeFilter(up.updated_at);"
    }
   ]
  },
  {
   "title": "ERRORS - UPDATE",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 7 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "select count(*) , created_at as time from uploads up where   up.is_processed = 2 and up.update = 2 and $__timeFilter(up.updated_at);"
    }
   ]
  },
  {
   "title": "ERRORS",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 7 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "select count(*) , created_at as time from uploads where   is_processed in (2) and $__timeFilter(updated_at);"
    }
   ]
  },
  {
   "title": "Files uploaded dummy",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "rawSql": "select \r\n  eg.name as `Grade` ,\r\n  stu.openemis_no as `Student ID`,  \r\n  stu.first_name as `Full Name`, \r\n  GROUP_CONCAT(DISTINCT edus.name) as `Subjects`,\r\n  IFNULL(LEFT(RIGHT(count(DISTINCT edus.id),8),4),'NA') as `Number of Subjects`,\r\n  DATE_FORMAT(stu.date_of_birth ,'%W, %M %e, %Y ' ) as `Date of Birth` , \r\n  g.name as `Gender`, \r\n  IFNULL(nati.name, 'NA') as `Nationality`,\r\n  IFNULL(idt.national_code, 'NA') as `Identity Type`,\r\n  IFNULL(LEFT(RIGHT(stu.identity_number,8),4),'NA') as `Identity Number`,\r\n  IFNULL (stu.identity_number,'na') as `Testing`,\r\n  ic.name as `Class` ,  \r\n  IFNULL(special_need_types.name, 'NA') as `Special Need Type`,\r\n  IFNULL(special_need_difficulties.name, 'NA') as `Special Need`,\r\n  IFNULL(stu.address, 'NA') as `Address`,\r\n  IFNULL(acp.name, 'NA') as `BMI Academic Period`,\r\n  DATE_FORMAT(bmit.date,'%W, %M %e, %Y ') as `BMI Date`,\r\n  IFNULL(bmit.height, 'NA') as `Height`,\r\n  IFNULL(bmit.weight, 'NA') as `Weight`,\r\n  IFNULL(acps.name, 'NA') as `Academic Periods`,\r\n  DATE_FORMAT(ist.start_date,'%W, %M %e, %Y ') as `Start Date`,\r\n  IFNULL(bro.name, 'NA') as `Birth Registrar Office`,\r\n  IFNULL(ds.name, 'NA') as `DS Office`,\r\n  stu.address_area_id,\r\n  IFNULL(sufu.first_name, 'NA') as `Father's Name`, \r\n  IFNULL(natif.name, 'NA') as `Father's Nationality`,\r\n  DATE_FORMAT(sufu.date_of_birth,'%W, %M %e, %Y ') as `Father's Date Of Birth`,\r\n  IFNULL(sufu.address , 'N/A') as `Father's Address`,\r\n  IFNULL(idtf.national_code, 'NA') as `Father's Identity Type`,\r\n  IFNULL(sufu.identity_number, 'NA') as `Father's Identity Number`,\r\n  IFNULL(sumu.first_name, 'N/A') as `Mothers's Name`,\r\n  IFNULL(natim.name, 'NA') as `Mothers's Nationality`, \r\n  DATE_FORMAT(sumu.date_of_birth,'%W, %M %e, %Y ') as `Mothers's Date Of Birth`,\r\n  IFNULL(sumu.address , 'N/A') as `Mothers's Address`,\r\n  IFNULL(idtm.national_code, 'NA') as `Mothers's Identity Type`,\r\n  IFNULL(sumu.identity_number, 'NA') as `Mother's Identity Number`,\r\n  IFNULL(sugu.first_name , 'N/A') as `Guardian's Name`,\r\n  IFNULL(natig.name, 'NA') as `Guardian's Nationality`,\r\n  DATE_FORMAT(sugu.date_of_birth,'%W, %M %e, %Y ') as `Guardian's Date Of Birth`,\r\n  IFNULL(sugu.address , 'N/A') as `Guardian's Address`,\r\n  IFNULL(idtg.national_code, 'NA') as `Guardian's Identity Type`,\r\n  IFNULL(sugu.identity_number, 'NA') as `Guardian's Identity Number`,\r\n  IFNULL(ubm.body_mass_index , 'N/A') as `BMI`\r\n  from (SELECT DISTINCT it.institution_id,it.student_id,it.education_grade_id,it.academic_period_id from institution_students it) ist\r\nleft join institutions i on ist.institution_id = i.id\r\nleft join education_grades  eg on eg.id = ist.education_grade_id\r\nleft join institution_class_students ics on ist.student_id = ics.student_id\r\nleft join institution_classes ic on   ic.id = ics.institution_class_id \r\nleft join security_users stu on ist.student_id = stu.id\r\nleft join student_guardians sgf on sgf.student_id = stu.id and sgf.guardian_relation_id = 1\r\nleft join security_users sufu on sgf.guardian_id = sufu.id\r\nleft join student_guardians sgm on sgm.student_id = stu.id  and sgm.guardian_relation_id = 2\r\nleft join security_users sumu on sgm.guardian_id = sumu.id\r\nleft join student_guardians sg on sg.student_id = stu.id   and sg.guardian_relation_id = 3\r\nleft join security_users sugu on sg.guardian_id = sugu.id\r\nleft join user_body_masses as ubm on ubm.security_user_id  = ist.student_id and \tubm.academic_period_id = ist.academic_period_id\r\nleft join genders g on stu.gender_id = g.id\r\nleft join area_administratives bro on stu.birthplace_area_id = bro.id \r\nleft join area_administratives ds on stu.address_area_id = ds.id  \r\nleft join nationalities nati on stu.nationality_id = nati.id \r\nleft join identity_types idt on stu.nationality_id = idt.id\r\nLeft join user_special_needs on ist.id = user_special_needs.security_user_id\r\nleft join special_need_types on special_need_types.id = user_special_needs.special_need_type_id\r\nleft join special_need_difficulties on special_need_difficulties.id = user_special_needs.special_need_difficulty_id\r\nleft join user_body_masses bmit on stu.id = bmit.security_user_id\r\nleft join academic_periods acp on acp.id = bmit.academic_period_id\r\nleft join academic_periods acps on acps.id = ist.academic_period_id\r\nleft join institution_subject_students iss on stu.id = iss.student_id\r\nleft join education_subjects edus on edus.id = iss.education_subject_id\r\nleft join nationalities natif on sufu.nationality_id = natif.id and sgf.guardian_relation_id = 1\r\nleft join nationalities natim on sumu.nationality_id = natif.id and sgm.guardian_relation_id = 2\r\nleft join nationalities natig on sugu.nationality_id = natif.id and sg.guardian_relation_id = 3\r\nleft join identity_types idtf on sufu.nationality_id = idtf.id and sgf.guardian_relation_id = 1\r\nleft join identity_types idtm on sumu.nationality_id = idtm.id and sgf.guardian_relation_id = 2\r\nleft join identity_types idtg on sugu.nationality_id = idtg.id and sgf.guardian_relation_id = 3\r\nwhere i.id = $code\r\ngroup by stu.openemis_no\r\n\r\n"
    }
   ]
  },
  {
   "title": "Student's List",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "rawSql": "select \r\n  eg.name as `Grade` ,\r\n  stu.openemis_no as `Student ID`,  \r\n  stu.first_name as `Full Name`, \r\n  GROUP_CONCAT(DISTINCT edus.name) as `Subjects`,\r\n  IFNULL(LEFT(RIGHT(count(DISTINCT edus.id),8),4),'NA') as `Number of Subjects`,\r\n  DATE_FORMAT(stu.date_of_birth ,'%W, %M %e, %Y ' ) as `Date of Birth` , \r\n  g.name as `Gender`, \r\n  IFNULL(nati.name, 'NA') as `Nationality`,\r\n  IFNULL(idt.national_code, 'NA') as `Identity Type`,\r\n  IFNULL(LEFT(RIGHT(stu.identity_number,8),4),'NA') as `Identity Number`,\r\n  IFNULL (stu.identity_number,'na') as `Testing`,\r\n  ic.name as `Class` ,  \r\n  IFNULL(special_need_types.name, 'NA') as `Special Need Type`,\r\n  IFNULL(special_need_difficulties.name, 'NA') as `Special Need`,\r\n  IFNULL(stu.address, 'NA') as `Address`,\r\n  IFNULL(acp.name, 'NA') as `BMI Academic Period`,\r\n  DATE_FORMAT(bmit.date,'%W, %M %e, %Y ') as `BMI Date`,\r\n  IFNULL(bmit.height, 'NA') as `Height`,\r\n  IFNULL(bmit.weight, 'NA') as `Weight`,\r\n  IFNULL(acps.name, 'NA') as `Academic Periods`,\r\n  DATE_FORMAT(ist.start_date,'%W, %M %e, %Y ') as `Start Date`,\r\n  IFNULL(bro.name, 'NA') as `Birth Registrar Office`,\r\n  IFNULL(ds.name, 'NA') as `DS Office`,\r\n  stu.address_area_id,\r\n  IFNULL(sufu.first_name, 'NA') as `Father's Name`, \r\n  IFNULL(natif.name, 'NA') as `Father's Nationality`,\r\n  DATE_FORMAT(sufu.date_of_birth,'%W, %M %e, %Y ') as `Father's Date Of Birth`,\r\n  IFNULL(sufu.address , 'N/A') as `Father's Address`,\r\n  IFNULL(idtf.national_code, 'NA') as `Father's Identity Type`,\r\n  IFNULL(sufu.identity_number, 'NA') as `Father's Identity Number`,\r\n  IFNULL(sumu.first_name, 'N/A') as `Mothers's Name`,\r\n  IFNULL(natim.name, 'NA') as `Mothers's Nationality`, \r\n  DATE_FORMAT(sumu.date_of_birth,'%W, %M %e, %Y ') as `Mothers's Date Of Birth`,\r\n  IFNULL(sumu.address , 'N/A') as `Mothers's Address`,\r\n  IFNULL(idtm.national_code, 'NA') as `Mothers's Identity Type`,\r\n  IFNULL(sumu.identity_number, 'NA') as `Mother's Identity Number`,\r\n  IFNULL(sugu.first_name , 'N/A') as `Guardian's Name`,\r\n  IFNULL(natig.name, 'NA') as `Guardian's Nationality`,\r\n  DATE_FORMAT(sugu.date_of_birth,'%W, %M %e, %Y ') as `Guardian's Date Of Birth`,\r\n  IFNULL(sugu.address , 'N/A') as `Guardian's Address`,\r\n  IFNULL(idtg.national_code, 'NA') as `Guardian's Identity Type`,\r\n  IFNULL(sugu.identity_number, 'NA') as `Guardian's Identity Number`,\r\n  IFNULL(ubm.body_mass_index , 'N/A') as `BMI`\r\n  from (SELECT DISTINCT it.institution_id,it.student_id,it.education_grade_id,it.academic_period_id from institution_students it) ist\r\nleft join institutions i on ist.institution_id = i.id\r\nleft join education_grades  eg on eg.id = ist.education_grade_id\r\nleft join institution_class_students ics on ist.student_id = ics.student_id\r\nleft join institution_classes ic on   ic.id = ics.institution_class_id \r\nleft join security_users stu on ist.student_id = stu.id\r\nleft join student_guardians sgf on sgf.student_id = stu.id and sgf.guardian_relation_id = 1\r\nleft join security_users sufu on sgf.guardian_id = sufu.id\r\nleft join student_guardians sgm on sgm.student_id = stu.id  and sgm.guardian_relation_id = 2\r\nleft join security_users sumu on sgm.guardian_id = sumu.id\r\nleft join student_guardians sg on sg.student_id = stu.id   and sg.guardian_relation_id = 3\r\nleft join security_users sugu on sg.guardian_id = sugu.id\r\nleft join user_body_masses as ubm on ubm.security_user_id  = ist.student_id and \tubm.academic_period_id = ist.academic_period_id\r\nleft join genders g on stu.gender_id = g.id\r\nleft join area_administratives bro on stu.birthplace_area_id = bro.id \r\nleft join area_administratives ds on stu.address_area_id = ds.id  \r\nleft join nationalities nati on stu.nationality_id = nati.id \r\nleft join identity_types idt on stu.nationality_id = idt.id\r\nLeft join user_special_needs on ist.id = user_special_needs.security_user_id\r\nleft join special_need_types on special_need_types.id = user_special_needs.special_need_type_id\r\nleft join special_need_difficulties on special_need_difficulties.id = user_special_needs.special_need_difficulty_id\r\nleft join user_body_masses bmit on stu.id = bmit.security_user_id\r\nleft join academic_periods acp on acp.id = bmit.academic_period_id\r\nleft join academic_periods acps on acps.id = ist.academic_period_id\r\nleft join institution_subject_students iss on stu.id = iss.student_id\r\nleft join education_subjects edus on edus.id = iss.education_subject_id\r\nleft join nationalities natif on sufu.nationality_id = natif.id and sgf.guardian_relation_id = 1\r\nleft join nationalities natim on sumu.nationality_id = natif.id and sgm.guardian_relation_id = 2\r\nleft join nationalities natig on sugu.nationality_id = natif.id and sg.guardian_relation_id = 3\r\nleft join identity_types idtf on sufu.nationality_id = idtf.id and sgf.guardian_relation_id = 1\r\nleft join identity_types idtm on sumu.nationality_id = idtm.id and sgf.guardian_relation_id = 2\r\nleft join identity_types idtg on sugu.nationality_id = idtg.id and sgf.guardian_relation_id = 3\r\nwhere i.id = $code\r\ngroup by stu.openemis_no\r\n\r\n"
    }
   ]
  },
  { "title": "Institution Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Panel Title",
   "type": "table-old",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "rawSql": "SELECT  i.name as `School Name` , i.code as `Census Code` ,  i.address  as `Address`, a.name as `Zone` from institutions i\ninner join areas a on a.id = i.area_id\nwhere i.id =  $code\n"
    }
   ]
  },
  {
   "title": "Institution Information",
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {
     "rawSql": "select * from institution_info_view where institution_id = '$insid'"
    }
   ]
  },
  {
   "title": "Students gender breakdown",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 33 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "select \n     ug.name as metric ,count(*) as value ,\n    $__time(su.created, '1h')\n    from (SELECT DISTINCT it.institution_id,it.student_id,it.education_grade_id,it.academic_period_id from institution_students it) ist\n inner join institutions as inst on ist.institution_id = inst.id\n inner join security_users as su on su.id = ist.student_id\n inner join areas as ia on inst.area_id = ia.id\n inner join genders as ug on ug.id = su.gender_id\n where inst.id = $code \ngroup by ug.id;"
    }
   ]
  },
  {
   "title": "Differently Able Students",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 9, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  modified AS \"time\",\n  id\nFROM academic_period_levels\nWHERE\n  $__timeFilter(modified)\nORDER BY modified"
    }
   ]
  },
  {
   "title": "National level Student's BMI status",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 6, "x": 16, "y": 33 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "select \n    count(CASE WHEN ubm.body_mass_index <  13 THEN ubm.body_mass_index END) as `Underweight`,\n    count(CASE WHEN ubm.body_mass_index > 13 and ubm.body_mass_index <= 16  THEN ubm.body_mass_index END) as `Normal`  ,\n    count(CASE WHEN ubm.body_mass_index > 16 and ubm.body_mass_index <= 18.25  THEN ubm.body_mass_index END) as `Overweight`,\n    count(CASE WHEN ubm.body_mass_index > 18.25  THEN ubm.body_mass_index END) as `Severely obese`,\n    $__time(ins.created, '1h')\n    from (SELECT DISTINCT it.institution_id,it.student_id,it.education_grade_id,it.academic_period_id from institution_students it) inst\n    inner join institutions as ins on ins.id = inst.institution_id\n    inner join user_body_masses as ubm on ubm.security_user_id  = inst.student_id and \tubm.academic_period_id = inst.academic_period_id\n    where ins.id = $code;\n "
    }
   ]
  },
  {
   "title": "Number of Students ",
   "type": "graph",
   "gridPos": { "h": 7, "w": 14, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select \n    (count(CASE WHEN eg.code = 'G1' THEN ist.student_id END)) as `G-1` ,  \n    (count(CASE WHEN eg.code = 'G2' THEN ist.student_id END)) as `G-2` ,\n    (count(CASE WHEN eg.code = 'G3' THEN ist.student_id END)) as `G-3` ,\n    (count(CASE WHEN eg.code = 'G4' THEN ist.student_id END)) as `G-4` ,\n    (count(CASE WHEN eg.code = 'G5' THEN ist.student_id END)) as `G-5` ,\n    (count(CASE WHEN eg.code = 'G6' THEN ist.student_id END)) as `G-6` ,\n    (count(CASE WHEN eg.code = 'G7' THEN ist.student_id END)) as `G-7` ,\n    (count(CASE WHEN eg.code = 'G8' THEN ist.student_id END)) as `G-8` ,\n    (count(CASE WHEN eg.code = 'G9' THEN ist.student_id END)) as `G-9` ,\n    (count(CASE WHEN eg.code = 'G10' THEN ist.student_id END)) as `G-10` ,\n    (count(CASE WHEN eg.code = 'G11' THEN ist.student_id END)) as `G-11` ,\n    (count(CASE WHEN eg.code like \"%12%\" THEN ist.student_id END)) as `G-12` ,\n    (count(CASE WHEN eg.code like \"%13%\" THEN ist.student_id END)) as `G-13` ,\n    $__time(su.created, '1h')\n    from (SELECT DISTINCT it.institution_id,it.student_id,it.education_grade_id,it.academic_period_id from institution_students it) ist\n inner join institutions as inst on ist.institution_id = inst.id\n inner join security_users as su on su.id = ist.student_id\n inner join areas as ia on inst.area_id = ia.id\n inner join education_grades as eg on eg.id = ist.education_grade_id\n where inst.id = \"$code\"  \ngroup by inst.id;\n \n"
    }
   ]
  },
  {
   "title": "Total Students",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 41 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "select count(*)  \nfrom (SELECT DISTINCT it.institution_id,it.student_id,it.education_grade_id,it.academic_period_id from institution_students it) ist\n-- inner join institutions i on ist.institution_id = i.id\ninner join security_users stu on ist.student_id = stu.id\n-- inner join education_grades eg on eg.id = ist.education_grade_id\nwhere  ist.institution_id = $code"
    }
   ]
  },
  {
   "title": "Total male Students",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 14, "y": 46 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "select count(*) from (SELECT DISTINCT it.institution_id,it.student_id,it.education_grade_id,it.academic_period_id from institution_students it) ist\ninner join institutions i on ist.institution_id = i.id\nleft join security_users stu on ist.student_id = stu.id\nwhere  i.id = $code\nand stu.gender_id = 1"
    }
   ]
  },
  {
   "title": "Total female Students",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 46 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "select count(*) from (SELECT DISTINCT it.institution_id,it.student_id,it.education_grade_id,it.academic_period_id from institution_students it) ist\ninner join institutions i on ist.institution_id = i.id\nleft join security_users stu on ist.student_id = stu.id\nwhere  i.id = $code\nand stu.gender_id = 2"
    }
   ]
  },
  {
   "title": "Students among Schools All Island",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 11, "w": 14, "x": 0, "y": 48 },
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT openemis.institutions.name,openemis.institutions.code, openemis.institutions.latitude,openemis.institutions.longitude , ia.name as Zone , FORMAT(COUNT(*),0) as NumberOfStudents \n FROM\n      (SELECT count(openemis.institution_students.modified)\n         FROM openemis.institution_students \n       ) institution_students  \n       inner join openemis.institutions \n       inner join openemis.institution_students \n     on openemis.institution_students.institution_id = openemis.institutions.id \n     inner join openemis.areas as ia on openemis.institutions.area_id = ia.id\n     inner join openemis.areas as pa on pa.id = ia.parent_id\n      where institutions.latitude > 0 and openemis.institutions.id  = $code\n     GROUP BY openemis.institution_students.institution_id\n     "
    }
   ]
  },
  {
   "title": "Count of Students by Subjects",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 14, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(<time_column>) as time_sec,\n  <value column> as value,\n  <series name column> as metric\nFROM <table name>\nWHERE $__timeFilter(time_column)\nORDER BY <time_column> ASC\n"
    }
   ]
  },
  {
   "title": "Number of Students By Grade dummy",
   "type": "table",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 55 },
   "targets": [
    {
     "rawSql": "select `G-1`,`G-2`,`G-3`,`G-4`,`G-5`,`G-6`,`G-7`,`G-8`,`G-9`,`G-10`,`G-11`,`G-12`,`G-13`, now() as time_sec from  students_count_by_grade_view where  institution_id = '$insid'"
    }
   ]
  },
  {
   "title": "Student Count List by Classes",
   "type": "table-old",
   "gridPos": { "h": 6, "w": 14, "x": 0, "y": 59 },
   "targets": [
    {
     "rawSql": "\nselect eg.name as `Grade` , ic.name as `Class` , ct.first_name as `Class Teacher`,  format(count(*),0)   as `No of Students`  \nfrom (SELECT DISTINCT it.institution_id,it.student_id,it.education_grade_id,it.academic_period_id from institution_students it) ist\ninner join institutions i on ist.institution_id = i.id\ninner join security_users stu on ist.student_id = stu.id\ninner join education_grades eg on eg.id = ist.education_grade_id\ninner join institution_student_admission isa on isa.student_id = ist.student_id\ninner join institution_classes as ic on ic.id = isa.institution_class_id\nleft join security_users ct on ct.id = ic.staff_id\nwhere  i.id = $code\ngroup by ic.name"
    }
   ]
  }
 ]
}