{
 "title": "School - Bulkupload",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "grade",
    "label": "Grade",
    "query": "select code from education_grades"
   },
   {
    "name": "insId",
    "query": "select security_group_institutions.institution_id from security_users inner join security_group_users on security_group_users.security_user_id = security_users.id inner join security_group_institutions on security_group_institutions.security_group_id = security_group_users.security_group_id where  security_users.username = '${__user.login}'  group by security_group_institutions.institution_id limit 1"
   },
   {
    "name": "class",
    "label": "Classes",
    "query": "select name from institution_classes where institution_id = $insId"
   }
  ]
 },
 "panels": [
  { "title": "Bulk Upload Progress", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "UPLOADS",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "select count(*) , created_at as time from uploads up \ninner join institution_classes ic on up.institution_class_id = ic.id\ninner join institutions i on ic.institution_id = i.id \ninner join institution_class_grades icg on ic.id = icg.institution_class_id\ninner join education_grades eg on eg.id = icg.education_grade_id\nwhere  $__timeFilter(updated_at) and i.id = '$insId';"
    }
   ]
  },
  {
   "title": "PROCESSED",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "select count(*) , created_at as time from uploads up \ninner join institution_classes ic on up.institution_class_id = ic.id\ninner join institutions i on ic.institution_id = i.id \ninner join institution_class_grades icg on ic.id = icg.institution_class_id\ninner join education_grades eg on eg.id = icg.education_grade_id\nwhere   up.is_processed != 0 and $__timeFilter(updated_at) and i.id = '$insId';"
    }
   ]
  },
  {
   "title": "ERRORS",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "select count(*) , created_at as time from  uploads up \ninner join institution_classes ic on up.institution_class_id = ic.id\ninner join institutions i on ic.institution_id = i.id \ninner join institution_class_grades icg on ic.id = icg.institution_class_id\ninner join education_grades eg on eg.id = icg.education_grade_id\nwhere   is_processed in (2) and $__timeFilter(updated_at) and i.id = '$insId';"
    }
   ]
  },
  {
   "title": "ERRORS - UPDATE",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "select count(*) , created_at as time from  uploads up \ninner join institution_classes ic on up.institution_class_id = ic.id\ninner join institutions i on ic.institution_id = i.id \ninner join institution_class_grades icg on ic.id = icg.institution_class_id\ninner join education_grades eg on eg.id = icg.education_grade_id\nwhere   up.is_processed = 2 and up.update = 2 and $__timeFilter(up.updated_at) and i.id = '$insId';"
    }
   ]
  },
  {
   "title": "SUCCESS - UPDATE",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 7 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "select count(*) , created_at as time from  uploads up \ninner join institution_classes ic on up.institution_class_id = ic.id\ninner join institutions i on ic.institution_id = i.id \ninner join institution_class_grades icg on ic.id = icg.institution_class_id\ninner join education_grades eg on eg.id = icg.education_grade_id\nwhere up.update in  (1,3) and $__timeFilter(up.updated_at) and i.id = '$insId';"
    }
   ]
  },
  {
   "title": "PARTIAL SUCCESS-INSERT",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 7 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "select count(*) , created_at as time from  uploads up \ninner join institution_classes ic on up.institution_class_id = ic.id\ninner join institutions i on ic.institution_id = i.id \ninner join institution_class_grades icg on ic.id = icg.institution_class_id\ninner join education_grades eg on eg.id = icg.education_grade_id \nwhere up.insert = 3 and $__timeFilter(up.updated_at) and i.id = '$insId';"
    }
   ]
  },
  {
   "title": "SUCCESS-INSERT",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 7 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "select count(*) , created_at as time  from  uploads up \ninner join institution_classes ic on up.institution_class_id = ic.id\ninner join institutions i on ic.institution_id = i.id \ninner join institution_class_grades icg on ic.id = icg.institution_class_id\ninner join education_grades eg on eg.id = icg.education_grade_id\nwhere up.update = 1 and $__timeFilter(up.updated_at) and i.id = '$insId';"
    }
   ]
  },
  {
   "title": "EMAIL SENT",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 7 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "select count(*) , created_at as time  from  uploads up \ninner join institution_classes ic on up.institution_class_id = ic.id\ninner join institutions i on ic.institution_id = i.id \ninner join institution_class_grades icg on ic.id = icg.institution_class_id\ninner join education_grades eg on eg.id = icg.education_grade_id \nwhere up.is_email_sent in (1,2) and $__timeFilter(up.updated_at) and  i.id = '$insId';"
    }
   ]
  }
 ]
}