{
 "title": "School - Overview",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "grade",
    "label": "Grade",
    "query": "select code from education_grades"
   },
   {
    "name": "insId",
    "query": "select security_group_institutions.institution_id from security_users inner join security_group_users on security_group_users.security_user_id = security_users.id inner join security_group_institutions on security_group_institutions.security_group_id = security_group_users.security_group_id where  security_users.username = '${__user.login}'  group by security_group_institutions.institution_id limit 1"
   },
   {
    "name": "class",
    "label": "Classes",
    "query": "select name from institution_classes where institution_id = $insId"
   }
  ]
 },
 "panels": [
  { "title": "Institution Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "School",
   "type": "table-old",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT  i.name as `School Name` , i.code as `Census Code` ,  i.address  as `Address`, a.name as `Zone` from institutions i\ninner join areas a on a.id = i.area_id\nwhere i.id =  '$insId'\n"
    }
   ]
  },
  {
   "title": "Students gender breakdown",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 5 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "select \n     ug.name as metric ,count(*) as value ,\n    $__time(su.created, '1h')\n    from (SELECT DISTINCT it.institution_id,it.student_id,it.education_grade_id,it.academic_period_id from institution_students it) ist\n inner join institutions as inst on ist.institution_id = inst.id\n inner join security_users as su on su.id = ist.student_id\n inner join areas as ia on inst.area_id = ia.id\n inner join genders as ug on ug.id = su.gender_id\n where inst.id = '$insId' \ngroup by ug.id;"
    }
   ]
  },
  {
   "title": "Student's BMI status",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 5 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "select \n    count(CASE WHEN ubm.body_mass_index <  13 THEN ubm.body_mass_index END) as `Underweight`,\n    count(CASE WHEN ubm.body_mass_index > 13 and ubm.body_mass_index <= 16  THEN ubm.body_mass_index END) as `Normal`  ,\n    count(CASE WHEN ubm.body_mass_index > 16 and ubm.body_mass_index <= 18.25  THEN ubm.body_mass_index END) as `Overweight`,\n    count(CASE WHEN ubm.body_mass_index > 18.25  THEN ubm.body_mass_index END) as `Severely obese`, inst.created as time\n    from  institution_students inst\n    inner join institutions as ins on ins.id = inst.institution_id\n    inner join user_body_masses as ubm on ubm.security_user_id  = inst.student_id and \tubm.academic_period_id = inst.academic_period_id\n    where ins.id = '$insId';\n "
    }
   ]
  },
  {
   "title": "Total Students",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "select count(*)  \nfrom institution_students ist\n-- inner join institutions i on ist.institution_id = i.id\ninner join security_users stu on ist.student_id = stu.id\n-- inner join education_grades eg on eg.id = ist.education_grade_id\nwhere  ist.institution_id = '$insId'"
    }
   ]
  },
  {
   "title": "Total male Students",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 14, "y": 10 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "select count(*) from  institution_students ist\ninner join institutions i on ist.institution_id = i.id\nleft join security_users stu on ist.student_id = stu.id\nwhere  i.id = '$insId'\nand stu.gender_id = 1"
    }
   ]
  },
  {
   "title": "Total female Students",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 10 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "select count(*) from  institution_students ist\ninner join institutions i on ist.institution_id = i.id\nleft join security_users stu on ist.student_id = stu.id\nwhere  i.id = '$insId'\nand stu.gender_id = 2"
    }
   ]
  },
  {
   "title": "Number of Students ",
   "type": "graph",
   "gridPos": { "h": 7, "w": 14, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select \n    (count(CASE WHEN eg.code = 'G1' THEN ist.student_id END)) as `G-1` ,  \n    (count(CASE WHEN eg.code = 'G2' THEN ist.student_id END)) as `G-2` ,\n    (count(CASE WHEN eg.code = 'G3' THEN ist.student_id END)) as `G-3` ,\n    (count(CASE WHEN eg.code = 'G4' THEN ist.student_id END)) as `G-4` ,\n    (count(CASE WHEN eg.code = 'G5' THEN ist.student_id END)) as `G-5` ,\n    (count(CASE WHEN eg.code = 'G6' THEN ist.student_id END)) as `G-6` ,\n    (count(CASE WHEN eg.code = 'G7' THEN ist.student_id END)) as `G-7` ,\n    (count(CASE WHEN eg.code = 'G8' THEN ist.student_id END)) as `G-8` ,\n    (count(CASE WHEN eg.code = 'G9' THEN ist.student_id END)) as `G-9` ,\n    (count(CASE WHEN eg.code = 'G10' THEN ist.student_id END)) as `G-10` ,\n    (count(CASE WHEN eg.code = 'G11' THEN ist.student_id END)) as `G-11` ,\n    (count(CASE WHEN eg.code like \"%12%\" THEN ist.student_id END)) as `G-12` ,\n    (count(CASE WHEN eg.code like \"%13%\" THEN ist.student_id END)) as `G-13` ,\n    $__time(su.created, '1h')\n    from institution_students ist\n inner join institutions as inst on ist.institution_id = inst.id\n inner join security_users as su on su.id = ist.student_id\n inner join areas as ia on inst.area_id = ia.id\n inner join education_grades as eg on eg.id = ist.education_grade_id\n where inst.id = \"$code\"  \ngroup by inst.id;\n \n"
    }
   ]
  },
  {
   "title": "Count of Students by Subjects",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select count(*) as value , es.name  , iss.created as time from  institution_subject_students iss \ninner join institutions i on i.id = iss.institution_id \ninner join education_subjects es on es.id = iss.education_subject_id\ninner join education_grades eg on eg.id  = iss.education_grade_id\nwhere i.id = '$insId' and eg.code = '$grade'\ngroup by es.name"
    }
   ]
  }
 ]
}