{
 "title": "Zone - Bulk upload Progress",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "zone_id",
    "label": "Zone",
    "query": "SELECT a.id FROM openemis.security_users su inner join openemis.security_group_users sgu on sgu.security_user_id = su.id inner join openemis.security_groups sg on sg.id = sgu.security_group_id inner join openemis.security_group_areas sga on sg.id = sga.security_group_id  inner join openemis.areas a on sga.area_id = a.id where a.area_level_id = 3 and sgu.security_role_id = 14 and su.username =  '${__user.login}' limit 1"
   },
   {
    "name": "province_id",
    "label": "Zone",
    "query": "SELECT sga.area_id FROM openemis.security_users su inner join openemis.security_group_users sgu on sgu.security_user_id = su.id inner join openemis.security_groups sg on sg.id = sgu.security_group_id inner join openemis.security_group_areas sga on sg.id = sga.security_group_id  inner join openemis.areas a on sga.area_id = a.id where a.area_level_id = 3 and sgu.security_role_id = 14 and su.username =  '${__user.login}'"
   }
  ]
 },
 "panels": [
  { "title": "Overall", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Uploads",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "select count(*) as value , created_at as time from uploads up\ninner join institution_classes ic on  ic.id = up.institution_class_id\ninner join institutions i on i.id = ic.institution_id\ninner join areas ia on ia.id = i.area_id\ninner join areas pa on pa.id = ia.parent_id\nwhere $__timeFilter(up.updated_at) and ia.id  = '$zone_id'"
    }
   ]
  },
  {
   "title": "Processed files",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "select count(*) as value , created_at as time from uploads up\ninner join institution_classes ic on  ic.id = up.institution_class_id\ninner join institutions i on i.id = ic.institution_id\ninner join areas ia on ia.id = i.area_id\ninner join areas pa on pa.id = ia.parent_id\nwhere   up.is_processed != 0 and ia.id  = '$zone_id' and $__timeFilter(up.created_at);"
    }
   ]
  },
  {
   "title": "Un-Processed files",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "select count(*) as value , created_at as time from uploads up\ninner join institution_classes ic on  ic.id = up.institution_class_id\ninner join institutions i on i.id = ic.institution_id\ninner join areas ia on ia.id = i.area_id\ninner join areas pa on pa.id = ia.parent_id\nwhere   up.is_processed = 0 and  ia.id  = '$zone_id' and $__timeFilter(up.created_at);"
    }
   ]
  },
  {
   "title": "Processing",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "select count(*) as metric , created_at as time from uploads up\ninner join institution_classes ic on  ic.id = up.institution_class_id\ninner join institutions i on i.id = ic.institution_id\ninner join areas ia on ia.id = i.area_id\ninner join areas pa on pa.id = ia.parent_id\nwhere  up.is_processed = 3 and ia.id  = '$zone_id' and $__timeFilter(up.updated_at)"
    }
   ]
  },
  { "title": "Update", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Error Report Sent - Update Error",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 7 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "select count(*) , created_at as time from uploads up \ninner join institution_classes ic on  ic.id = up.institution_class_id\ninner join institutions i on i.id = ic.institution_id\ninner join areas ia on ia.id = i.area_id\ninner join areas pa on pa.id = ia.parent_id\nwhere up.update = 2 and ia.id  = '$zone_id'"
    }
   ]
  },
  {
   "title": "Success Report Sent - Update ",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 7 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "select count(*) , created_at as time from uploads up \ninner join institution_classes ic on  ic.id = up.institution_class_id\ninner join institutions i on i.id = ic.institution_id\ninner join areas ia on ia.id = i.area_id\ninner join areas pa on pa.id = ia.parent_id\nwhere up.update = 1 and ia.id  = '$zone_id'"
    }
   ]
  },
  {
   "title": "PARTIAL SUCCESS",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 7 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "select count(*) , created_at as time from uploads up \ninner join institution_classes ic on  ic.id = up.institution_class_id\ninner join institutions i on i.id = ic.institution_id\ninner join areas ia on ia.id = i.area_id\ninner join areas pa on pa.id = ia.parent_id\nwhere up.update = 3 and is_processed = 2 and ia.id  = '$zone_id'"
    }
   ]
  },
  { "title": "Insert", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Error Report Sent - Insert Error",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 13 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "select count(*) , created_at as time from uploads up \ninner join institution_classes ic on  ic.id = up.institution_class_id\ninner join institutions i on i.id = ic.institution_id\ninner join areas ia on ia.id = i.area_id\ninner join areas pa on pa.id = ia.parent_id\nwhere  up.insert = 2 and ia.id  = '$zone_id'"
    }
   ]
  },
  {
   "title": "Success Report Sent - Insert ",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 13 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "select count(*) , created_at as time from uploads up \ninner join institution_classes ic on  ic.id = up.institution_class_id\ninner join institutions i on i.id = ic.institution_id\ninner join areas ia on ia.id = i.area_id\ninner join areas pa on pa.id = ia.parent_id\nwhere up.insert = 1 and ia.id  = '$zone_id'"
    }
   ]
  },
  {
   "title": "PARTIAL SUCCESS",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 13 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "select count(*) , created_at as time from uploads up \ninner join institution_classes ic on  ic.id = up.institution_class_id\ninner join institutions i on i.id = ic.institution_id\ninner join areas ia on ia.id = i.area_id\ninner join areas pa on pa.id = ia.parent_id\nwhere   up.insert = 3 and up.is_processed = 2 and ia.id  = '$zone_id'"
    }
   ]
  }
 ]
}