{
 "title": "Provinces - Summery",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "province_id",
    "label": "Province",
    "query": "SELECT sga.area_id FROM openemis.security_users su inner join openemis.security_group_users sgu on sgu.security_user_id = su.id inner join openemis.security_groups sg on sg.id = sgu.security_group_id inner join openemis.security_group_areas sga on sg.id = sga.security_group_id  inner join openemis.areas a on sga.area_id = a.id where a.area_level_id = 2 and sgu.security_role_id = 13 and su.username =  '${__user.login}'"
   },
   {
    "name": "zone",
    "label": "Zone",
    "query": "select name from areas where parent_id='$province_id' and area_level_id=3"
   }
  ]
 },
 "panels": [
  { "title": "Total Progress", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Students  added to the System ",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT count(*)  as NumberOfStudent \nfrom institution_students ist\ninner join institutions on ist.institution_id = institutions.id\ninner join areas as ia on ia.id = institutions.area_id\ninner join areas as pa on ia.parent_id = pa.id\nwhere pa.id = '$province_id' and ia.name in($zone)"
    }
   ]
  },
  {
   "title": "Grade 1",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "\nselect\n    count(*)\nfrom institution_students  ic\n inner join institutions ist on ist.id = ic.institution_id\n inner join institution_class_grades as icg on ist.id = icg.institution_class_id\n inner join education_grades as eg on eg.id = icg.education_grade_id and eg.code = 'G1'\n inner join areas as ia on ist.area_id = ia.id\ninner join areas as pa on ia.parent_id = pa.id\nwhere pa.id = '$province_id' and ia.name in($zone)"
    }
   ]
  },
  {
   "title": "Grade 2-5",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "select\n    count(*)\nfrom institution_students  ic\n inner join institutions ist on ist.id = ic.institution_id\n inner join institution_class_grades as icg on ist.id = icg.institution_class_id\n inner join education_grades as eg on eg.id = icg.education_grade_id and eg.code in ('G2','G3','G4','G5')\n  inner join areas as ia on ist.area_id = ia.id\ninner join areas as pa on ia.parent_id = pa.id\nwhere pa.id = '$province_id'  and ia.name in($zone)"
    }
   ]
  },
  {
   "title": "Grade 6-11",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "select\n    count(*)\n     from institution_students  ic\n inner join institutions ist on ist.id = ic.institution_id\n inner join institution_class_grades as icg on ist.id = icg.institution_class_id\n inner join education_grades as eg on eg.id = icg.education_grade_id and eg.code  = 'G6'\n  inner join areas as ia on ist.area_id = ia.id\ninner join areas as pa on ia.parent_id = pa.id\nwhere pa.id = '$province_id'  and ia.name in($zone)"
    }
   ]
  },
  {
   "title": "Grade 12-13",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "select\n    count(*)\n    from  institution_students ic\n inner join institutions ist on ist.id = ic.institution_id\n inner join institution_class_grades as icg on ist.id = icg.institution_class_id\n inner join education_grades as eg on eg.id = icg.education_grade_id and eg.code in ('12ARTS','13ARTS','G13Arts(2)','G13(POOL)','12MATHS','13MATHS','G13Maths(2)','G13M(POOL)','12BIO','13BIO','G13B(POOL)','G13BIO(2)','12TEC','13TEC','G13T(POOL)','G13T(POOL)','12COM','13COM','G13C(POOL)','G13COM(2)')\n  inner join areas as ia on ist.area_id = ia.id\ninner join areas as pa on ia.parent_id = pa.id\nwhere pa.id = '$province_id'  and ia.name in($zone)\n "
    }
   ]
  },
  {
   "title": "National Schools not Started Data entry ",
   "type": "table-old",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": "     SELECT  ist.name as School_Name, ist.code as Census_No, ia.name as Zone\n FROM  institutions ist\n inner join areas as ia on ist.area_id = ia.id\ninner join areas as pa on ia.parent_id = pa.id\nwhere pa.id = '$province_id' && ist.id not in (SELECT  institution_id  from institution_students ) \n\n    \n\n"
    }
   ]
  },
  {
   "title": "National Schools Started Data entry ",
   "type": "table-old",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT openemis.institutions.name as School_Name,openemis.institutions.code as Census_No, ia.name as Zone , FORMAT(COUNT(*),0) as NumberOfStudents \n FROM\n      (SELECT count(openemis.institution_students.modified)\n         FROM openemis.institution_students\n       ) institution_students  inner join openemis.institutions inner join openemis.institution_students \n     on openemis.institution_students.institution_id = openemis.institutions.id \n     inner join openemis.areas ia on openemis.institutions.area_id = ia.id\n     inner join areas pa on pa.id = ia.parent_id\n  where pa.id = '$province_id'  and ia.name in($zone)\n     GROUP BY openemis.institution_students.institution_id"
    }
   ]
  }
 ]
}